BW: 0.02
DATASET_A: /roi3_e047/00/peaklists
DATASET_R: /roi3_e047/00/peaklists
DEV: 1.0
FILE_NAMES: !!python/tuple
- "C:/Users/doomu/OneDrive/\u0420\u0430\u0431\u043E\u0447\u0438\u0439 \u0441\u0442\
  \u043E\u043B/Test_2/roi_align_/roi_align__specdata.hdf5"
- "C:/Users/doomu/OneDrive/\u0420\u0430\u0431\u043E\u0447\u0438\u0439 \u0441\u0442\
  \u043E\u043B/Test_2/roi_align_50_3/roi_align_50_3_specdata.hdf5"
NDOTS: 100000
REF: 193.07712
